DirectoryPath: "public"
EnforceHTTPS: true
CheckInternalHash: false

# Ignore specific URLs that are known to have issues or require authentication
IgnoreURLs:
- "douglashellinger.com"
- "https://(www.)?linkedin.com/in/[a-z]+"
- "https://linuxconfig.org/how-to-install-the-nvidia-drivers-on-ubuntu-20-04-focal-fossa-linux"
- "https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/"
- "^/misc/js/script.js$"
- "https://www.udemy.com/course/writing-for-business/"
- "https://www.netfilter.org/documentation/HOWTO/NAT-HOWTO-6.html"
- "http://your.elastic.ip.address/admin"
- "https://askubuntu.com/a/1245075/278849"
- "https://github.com/projectatomic/containerd/blob/master/docs/cli.md"
- "https://www.wowthemes.net"
- "https://marketplace.visualstudio.com/items"
# Add medium.com URLs that commonly return 403 due to WAF
- "https://(www.)?medium.com/@.*"
- "https://.*\\.medium\\.com/.*"

# Ignore HTTPS enforcement for specific HTTP-only URLs
IgnoreHTTPS:
- "http://butunclebob.com/ArticleS.UncleBob.PrinciplesOfOod"

# Image alt attribute handling
IgnoreAltMissing: true

# Cache configuration
CacheExpires: "6h"

# Directory and link handling
IgnoreDirectoryMissingTrailingSlash: true
IgnoreCanonicalBrokenLinks: true

# External link timeout and retry configuration
ExternalTimeout: 15
RedirectLimit: 5

# Custom HTTP headers to avoid bot detection
HTTPHeaders:
  User-Agent: "Mozilla/5.0 (compatible; Link-Checker/1.0; +https://douglashellinger.com)"
  Accept: "*/*"
  Range: "bytes=0-0"