DirectoryPath: "public"
EnforceHTTPS: true
CheckInternalHash: false
IgnoreURLs:
- "douglashellinger.com"
- "https://linkedin.com/in/doughellinger"
- "^/misc/js/script.js$"
IgnoreAltMissing: true
CacheExpires: "6h"
IgnoreDirectoryMissingTrailingSlash: true
IgnoreCanonicalBrokenLinks: true
ExternalTimeout: 5