name: Build and test Hugo site

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container: ghcr.io/doughgle/docs-as-code:main

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      - name: Show tool versions
        run: |
          echo -n "mdshell " && mdspell --version
          echo -n "write-good " && write-good --version
          markdownlint-cli2 | head -1
          htmltest --version
          hugo version

      - run: pwd;ls -lah
        working-directory: ./content

      - name: Check spelling
        run: mdspell --report --en-gb **/*.md
        working-directory: content

      # Build the site
      - run: hugo