name: Build and test Hugo site

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container: ghcr.io/doughgle/docs-as-code:main

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Show tool versions
        run: |
          echo -n "write-good " && write-good --version
          markdownlint-cli2 | head -1
          htmltest --version
          hugo version

      - name: Check prose
        shell: bash
        run: |
          shopt -s globstar
          write-good --parse **/*.md
        continue-on-error: true
        working-directory: content

      - name: Lint Markdown
        run: markdownlint-cli2 '**/*.md'
        continue-on-error: true
        working-directory: content

      - name: Build Site (including drafts and future posts)
        run: hugo --buildDrafts --buildFuture
        if: ${{ github.ref != 'refs/heads/main' }}

      - name: Build Site (excluding drafts and future posts)
        run: hugo --minify
        if: ${{ github.ref == 'refs/heads/main' }}

      # htmltest (configured in .htmltest.yml)
      - name: Test HTML
        run: htmltest

      - name: Publish HTML
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
        if: ${{ github.ref == 'refs/heads/main' }}