name: Medium

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Markdown file to publish'
        required: true
        type: string
        default: 'content/blog/hello-world/index.md'

jobs:
  post-to-medium:
    name: Post to Medium
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@v3

      - name: Replace Local Images With Public URLs
        run: |
          file="${{ inputs.file }}"
          match='(.*!\[.*\]\()(.*)\).*'
          sed --in-place --regexp-extended \
              --expression="s|$match|\1$(dirname "$file")/\2)|;" \
              --expression="s|content|https://www.douglashellinger.com|g" \
              "$file"

      - name: Derive Canonical URL
        id: derive_canonical_url
        run: |
          echo "canonical_url=https://www.douglashellinger.com/${{ inputs.file }}" \
          | sed --expression 's|content/||' \
          --expression 's|index.md||' \
          >> "$GITHUB_OUTPUT"

      - name: Create Medium Post
        uses: philips-software/post-to-medium-action@v0.6.0
        with:
          integration_token: "${{ secrets.MEDIUM_INTEGRATION_TOKEN }}"
          file: "${{ inputs.file }}"
          content_format: "markdown"
          notify_followers: "false"
          license: "cc-40-by"
          publish_status: "draft"
          parse_frontmatter: "true"
          canonical_url: ${{ steps.derive_canonical_url.outputs.canonical_url }}